-- KPIs SQL Queries for Brazilian E-commerce Analytics
-- Author: Generated by GitHub Copilot (GPT-4.1)
-- Data model: Star schema (see docs/data_model.md)


SELECT d.date, d.year, d.month, SUM(f.total_revenue) AS revenue
FROM gold.fact_daily_sales f
JOIN gold.dim_date d ON f.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY d.year, d.month, d.date
ORDER BY d.date;

SELECT d.year, d.month,
       SUM(f.total_revenue) AS revenue,
       LAG(SUM(f.total_revenue)) OVER (ORDER BY d.year, d.month) AS revenue_prev_year,
       (SUM(f.total_revenue) - LAG(SUM(f.total_revenue)) OVER (ORDER BY d.year, d.month)) AS diff_vs_prev_year,
      ROUND((100.0 * (SUM(f.total_revenue) - LAG(SUM(f.total_revenue)) OVER (ORDER BY d.year, d.month)) / NULLIF(LAG(SUM(f.total_revenue)) OVER (ORDER BY d.year, d.month),0))::numeric, 2) AS pct_change
FROM gold.fact_daily_sales f
JOIN gold.dim_date d ON f.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY d.year, d.month
ORDER BY d.year, d.month;

SELECT p.product_id, p.category_id, dpc.product_category_name, SUM(fpp.total_revenue) AS revenue
FROM gold.fact_product_performance fpp
JOIN gold.dim_products p ON fpp.product_id = p.product_id
JOIN gold.dim_product_categories dpc ON p.category_id = dpc.category_id
JOIN gold.dim_date d ON fpp.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY p.product_id, p.category_id, dpc.product_category_name
ORDER BY revenue DESC
LIMIT 10;


WITH first_orders AS (
  SELECT c.customer_unique_id, MIN(o.date_id) AS first_order_date
  FROM gold.fact_orders o
  JOIN gold.dim_customers c ON o.customer_id = c.customer_id
  GROUP BY c.customer_unique_id
)
SELECT d.year, d.month,
       COUNT(DISTINCT CASE WHEN c.customer_unique_id IS NOT NULL AND o.date_id = fo.first_order_date THEN c.customer_unique_id END) AS new_customers,
       COUNT(DISTINCT CASE WHEN c.customer_unique_id IS NOT NULL AND o.date_id > fo.first_order_date THEN c.customer_unique_id END) AS returning_customers
FROM gold.fact_orders o
JOIN gold.dim_date d ON o.date_id = d.date_id
JOIN gold.dim_customers c ON o.customer_id = c.customer_id
JOIN first_orders fo ON c.customer_unique_id = fo.customer_unique_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY d.year, d.month
ORDER BY d.year, d.month;

SELECT d.year, d.month, AVG(fcl.avg_order_value) AS avg_order_value
FROM gold.fact_customer_lifetime fcl
JOIN gold.dim_date d ON fcl.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY d.year, d.month
ORDER BY d.year, d.month;

SELECT d.year, d.month,
       SUM(fds.total_orders) AS total_orders,
       SUM(fds.unique_customers) AS unique_customers,
       ROUND(100.0 * SUM(fds.total_orders) / NULLIF(SUM(fds.unique_customers),0),2) AS conversion_rate_pct
FROM gold.fact_daily_sales fds
JOIN gold.dim_date d ON fds.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY d.year, d.month
ORDER BY d.year, d.month;

SELECT customer_unique_id,
       MAX(date_id) AS last_order_date,
       COUNT(order_id) AS frequency,
       SUM(order_amount) AS monetary
FROM gold.fact_orders
JOIN gold.dim_date d ON gold.fact_orders.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY customer_unique_id;


WITH cohort AS (
  SELECT c.customer_unique_id, MIN(o.date_id) AS cohort_month
  FROM gold.fact_orders o
  JOIN gold.dim_customers c ON o.customer_id = c.customer_id
  GROUP BY c.customer_unique_id
),
orders AS (
  SELECT c.customer_unique_id, o.date_id
  FROM gold.fact_orders o
  JOIN gold.dim_customers c ON o.customer_id = c.customer_id
)
SELECT c.cohort_month, d.year, d.month, COUNT(DISTINCT o.customer_unique_id) AS retained_customers
FROM cohort c
JOIN orders o ON c.customer_unique_id = o.customer_unique_id
JOIN gold.dim_date d ON o.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY c.cohort_month, d.year, d.month
ORDER BY c.cohort_month, d.year, d.month;

WITH cohort_ltv AS (
  SELECT customer_unique_id, MIN(date_id) AS cohort_month, SUM(order_amount) AS ltv
  FROM gold.fact_orders
  JOIN gold.dim_date d ON gold.fact_orders.date_id = d.date_id
  WHERE (d.year = %(year)s OR %(year)s IS NULL)
    AND (d.month = %(month)s OR %(month)s IS NULL)
  GROUP BY customer_unique_id
)
SELECT cohort_month, AVG(ltv) AS avg_ltv
FROM cohort_ltv
GROUP BY cohort_month
ORDER BY cohort_month;

-- END OF KPI QUERIES
-- KPIs additionnels pour l'e-commerce brésilien

-- 1. Taux d’annulation des commandes
SELECT d.year, d.month,
       SUM(CASE WHEN o.order_status = 'canceled' THEN 1 ELSE 0 END) AS canceled_orders,
       COUNT(o.order_id) AS total_orders,
       ROUND(100.0 * SUM(CASE WHEN o.order_status = 'canceled' THEN 1 ELSE 0 END) / NULLIF(COUNT(o.order_id),0),2) AS cancel_rate_pct
FROM gold.fact_orders o
JOIN gold.dim_date d ON o.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY d.year, d.month
ORDER BY d.year, d.month;

-- 2. Délai moyen de livraison
SELECT d.year, d.month,
       AVG(o.delivery_time_days) AS avg_delivery_time
FROM gold.fact_orders o
JOIN gold.dim_date d ON o.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY d.year, d.month
ORDER BY d.year, d.month;

-- 3. Score moyen des avis clients
SELECT d.year, d.month,
       AVG(r.review_score) AS avg_review_score
FROM gold.fact_order_reviews r
JOIN gold.dim_date d ON r.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY d.year, d.month
ORDER BY d.year, d.month;

-- 4. Nombre de commandes par état
SELECT s.state, d.year, d.month, COUNT(o.order_id) AS order_count
FROM gold.fact_orders o
JOIN gold.dim_sellers s ON o.seller_id = s.seller_id
JOIN gold.dim_date d ON o.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY s.state, d.year, d.month
ORDER BY d.year, d.month, s.state;

-- 5. CA par seller
SELECT s.seller_id, s.seller_name, d.year, d.month, SUM(o.order_amount) AS revenue
FROM gold.fact_orders o
JOIN gold.dim_sellers s ON o.seller_id = s.seller_id
JOIN gold.dim_date d ON o.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY s.seller_id, s.seller_name, d.year, d.month
ORDER BY revenue DESC;

-- 1. Taux d’annulation YoY
SELECT d.year, d.month,
       ROUND(100.0 * SUM(CASE WHEN o.order_status = 'canceled' THEN 1 ELSE 0 END) / NULLIF(COUNT(o.order_id),0),2) AS cancel_rate_pct,
       LAG(ROUND(100.0 * SUM(CASE WHEN o.order_status = 'canceled' THEN 1 ELSE 0 END) / NULLIF(COUNT(o.order_id),0),2)) OVER (ORDER BY d.year, d.month) AS cancel_rate_prev_year,
       ROUND(100.0 * (ROUND(100.0 * SUM(CASE WHEN o.order_status = 'canceled' THEN 1 ELSE 0 END) / NULLIF(COUNT(o.order_id),0),2) - COALESCE(LAG(ROUND(100.0 * SUM(CASE WHEN o.order_status = 'canceled' THEN 1 ELSE 0 END) / NULLIF(COUNT(o.order_id),0),2)) OVER (ORDER BY d.year, d.month),0)) / NULLIF(LAG(ROUND(100.0 * SUM(CASE WHEN o.order_status = 'canceled' THEN 1 ELSE 0 END) / NULLIF(COUNT(o.order_id),0),2)) OVER (ORDER BY d.year, d.month),0),2) AS pct_change
FROM gold.fact_orders o
JOIN gold.dim_date d ON o.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY d.year, d.month
ORDER BY d.year, d.month;

-- 2. Délai moyen de livraison YoY
SELECT d.year, d.month,
       AVG(o.delivery_time_days) AS avg_delivery_time,
       LAG(AVG(o.delivery_time_days)) OVER (ORDER BY d.year, d.month) AS avg_delivery_time_prev_year,
       ROUND(100.0 * (AVG(o.delivery_time_days) - LAG(AVG(o.delivery_time_days)) OVER (ORDER BY d.year, d.month)) / NULLIF(LAG(AVG(o.delivery_time_days)) OVER (ORDER BY d.year, d.month),0),2) AS pct_change
FROM gold.fact_orders o
JOIN gold.dim_date d ON o.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY d.year, d.month
ORDER BY d.year, d.month;

-- 3. Score moyen des avis YoY
SELECT d.year, d.month,
       AVG(r.review_score) AS avg_review_score,
       LAG(AVG(r.review_score)) OVER (ORDER BY d.year, d.month) AS avg_review_score_prev_year,
       ROUND(100.0 * (AVG(r.review_score) - LAG(AVG(r.review_score)) OVER (ORDER BY d.year, d.month)) / NULLIF(LAG(AVG(r.review_score)) OVER (ORDER BY d.year, d.month),0),2) AS pct_change
FROM gold.fact_order_reviews r
JOIN gold.dim_date d ON r.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY d.year, d.month
ORDER BY d.year, d.month;

-- 4. Nombre de commandes par état YoY
SELECT s.state, d.year, d.month,
       COUNT(o.order_id) AS order_count,
       LAG(COUNT(o.order_id)) OVER (PARTITION BY s.state ORDER BY d.year, d.month) AS order_count_prev_year,
       ROUND(100.0 * (COUNT(o.order_id) - LAG(COUNT(o.order_id)) OVER (PARTITION BY s.state ORDER BY d.year, d.month)) / NULLIF(LAG(COUNT(o.order_id)) OVER (PARTITION BY s.state ORDER BY d.year, d.month),0),2) AS pct_change
FROM gold.fact_orders o
JOIN gold.dim_sellers s ON o.seller_id = s.seller_id
JOIN gold.dim_date d ON o.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY s.state, d.year, d.month
ORDER BY d.year, d.month, s.state;

-- 5. CA par seller YoY
SELECT s.seller_id, s.seller_name, d.year, d.month,
       SUM(o.order_amount) AS revenue,
       LAG(SUM(o.order_amount)) OVER (PARTITION BY s.seller_id ORDER BY d.year, d.month) AS revenue_prev_year,
       ROUND(100.0 * (SUM(o.order_amount) - LAG(SUM(o.order_amount)) OVER (PARTITION BY s.seller_id ORDER BY d.year, d.month)) / NULLIF(LAG(SUM(o.order_amount)) OVER (PARTITION BY s.seller_id ORDER BY d.year, d.month),0),2) AS pct_change
FROM gold.fact_orders o
JOIN gold.dim_sellers s ON o.seller_id = s.seller_id
JOIN gold.dim_date d ON o.date_id = d.date_id
WHERE (d.year = %(year)s OR %(year)s IS NULL)
  AND (d.month = %(month)s OR %(month)s IS NULL)
GROUP BY s.seller_id, s.seller_name, d.year, d.month
ORDER BY revenue DESC;
